# --------------------------------
# Site settings
title: Razvan Negrea – Creative front-end developer, concept artist & illustrator
author: Razvan Negrea 
email: howl@wolfpilot.co
description: Front-end developer and freelance artist based in Rugby, UK. I specialise in WordPress development, CSS animation and pushing pixels.

# --------------------------------
# Environment Settings
environment: development
source: _src
destination: _site
baseurl: ""
url: "http://wolfpilot.local:4000"

# --------------------------------
# Paths
css: "/assets/css/style.css"
js: "/assets/js/scripts.js"

# --------------------------------
# Collections
collections:
  case-studies:
    output: true
    permalink: /:collection/:title/

defaults:
  -
    scope:
      path: ""
      type: "case-studies"
    values:
      layout: "case-study"

# --------------------------------
# Build settings
markdown: kramdown
safe: false
future: true
# paginate: 5

# Category Handling
category_dir: /
tag_dir: /tag/

# --------------------------------
# Social Networking
github:  wolfpilot
codepen: wolfpilot
deviantart: n-deed
linkedin: razvannegrea

# --------------------------------
# Includes & Excludes
exclude: [
  feed.xml,
  assets/js
]
include: [
  assets/fonts,
  CNAME
]