# --------------------------------
# Site settings
title: Razvan Negrea – Creative front-end developer, concept artist & illustrator
author: Razvan Negrea 
email: howl@wolfpilot.co.uk
description: Front-end developer and freelance artist based in Rugby, UK. I specialise in WordPress development, CSS animation and pushing pixels.

# --------------------------------
# Environment Settings
environment: production
source: _src
destination: _site
baseurl: ""
url: "http://www.wolfpilot.co.uk/"

# --------------------------------
# Paths
css: "/assets/css/main.min.css"
js: "/assets/js/main.min.js"

# --------------------------------
# Build settings
markdown: kramdown
safe: false
future: false
# paginate: 5
show_drafts: false
# highlighter: true

# Category Handling
category_dir: /
tag_dir: /tag/

# --------------------------------
# Social Networking
github:  wolfpilot
deviantart: n-deed
linkedin: razvannegrea

# --------------------------------
# Includes
exclude: [
  feed.xml,
  assets/js
]
include: [
  assets/fonts,
  CNAME
]