# --------------------------------
# Site settings
title: Portfolio Site
author: Razvan Negrea 
email: howl@wolfpilot.co.uk
description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque eius earum vero quae reiciendis qui dolores molestias velit, suscipit! Dolor nostrum ad dolorem delectus praesentium, reiciendis quas officiis, eius veniam.

# --------------------------------
# Environment Settings
environment: development
source: _src
destination: _site
baseurl: ""
url: "http://wolfpilot.local:4000"

# --------------------------------
# Paths
css: "/assets/css/style.css"
js: "/assets/js/scripts.js"

# --------------------------------
# Collections
collections:
  case-studies:
    output: true
    permalink: /:collection/:title/

defaults:
  -
    scope:
      path: ""
      type: "case-studies"
    values:
      layout: "case-study"

# --------------------------------
# Build settings
markdown: kramdown
safe: false
future: true
# paginate: 5

# Category Handling
category_dir: /
tag_dir: /tag/

# --------------------------------
# Social Networking
github:  wolfpilot
deviantart: n-deed
linkedin: razvannegrea

# --------------------------------
# Includes & Excludes
exclude: [
  feed.xml,
  assets/js
]
include: [
  assets/fonts,
  CNAME
]